# Generated by Django 3.2.16 on 2022-12-31 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Requester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_rides',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applied_rides',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transport_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.TextField()),
                ('delivery_at', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('flexible', models.BooleanField()),
                ('whom_to_deliver', models.TextField()),
                ('assets_quantity', models.IntegerField()),
                ('asset_types', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('TRAVEL_BAG', 'TRAVEL_BAG'), ('PACKAGE', 'PACKAGE')], max_length=20)),
                ('sensitivities', models.CharField(choices=[('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'), ('SENSITIVE', 'Sensitive'), ('NORMAL', 'NORMAL')], max_length=20)),
                ('status', models.CharField(choices=[('EXPIRED', 'EXPIRED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
