# Generated by Django 3.2.16 on 2022-12-31 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Requester', '0002_auto_20221231_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.TextField()),
                ('delivery_at', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('flexible', models.BooleanField(default=False)),
                ('assets_quantity', models.IntegerField()),
                ('travel_medium', models.CharField(choices=[('CAR', 'CAR'), ('BUS', 'BUS'), ('TRAIN', 'TRAIN')], max_length=20)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_info_rider', to=settings.AUTH_USER_MODEL)),
                ('transport_request', models.ManyToManyField(blank=True, to='Requester.Transport_Request')),
            ],
        ),
    ]
