# Generated by Django 3.2.16 on 2022-12-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Requester', '0003_travel_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applied_Rides',
        ),
    ]
