# Generated by Django 3.2.16 on 2022-12-31 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Requester', '0004_delete_applied_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_requester', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_rider', to=settings.AUTH_USER_MODEL)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requester.transport_request')),
            ],
        ),
    ]
